### ISSUE TITLE
how to apply dbscan on each group ?

### ISSUE THREAD

**Issue by ghost** [mraad/dbscan-scala#1]
hi @mraad 
now I have a dataframe that include vin,lat,lng etc
Next,filtter sub_dataframe from dataframe when i pick one vin,dbscan works well
but I  want to know how to apply dbscan on each vin ?
thank you very much

**Comment by mraad** [comment]
Thanks for your patience in my reply - in the current implementation there is no group by - thus the implementation is to take ALL the data - I recommend a "simpler" approach if the data in a group is smaller - use the groupby and per map partition - use a "regular" dbscan - hope that helps.

**Comment by ghost** [comment]
thanks
